import type { Metadata } from 'next';
import { AppConfigurations } from '@/configs/app-configurations/app.configurations';

import localFont from 'next/font/local';

const IRANSans = localFont({
  src: '../../public/fonts/IRANSansXV.woff',
});
export const metadata: Metadata = {
  title: 'local server',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IRANSans.className}>
        <main>
          <AppConfigurations>{children}</AppConfigurations>
        </main>
      </body>
    </html>
  );
}
